### ISSUE TITLE
运行报错，求解！

### ISSUE THREAD

**Issue by Justin666521** [haozhihang123/pytorc_classification_model#1]
Traceback (most recent call last):
  File "C:\Users\Sheldon\Desktop\pytorch\pytorc_classification_model-master\pytorch_classification_model\test.py", line 64, in <module>
    test()
  File "C:\Users\Sheldon\Desktop\pytorch\pytorc_classification_model-master\pytorch_classification_model\test.py", line 31, in test
    model = torch.load(model_file)
  File "C:\Users\Sheldon\.conda\envs\pytorch\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Sheldon\.conda\envs\pytorch\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Sheldon\.conda\envs\pytorch\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model/model_10.pth'

**Comment by haozhihang123** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './model/model_10.pth'这句话的意思是程序找不到你的权重，也就是找不到'./model/model_10.pth'这个文件，你把这个文件的路径设置好了就行了。
